name: main-1


on:
    workflow_dispatch


jobs:
    first-job:
        runs-on: ubuntu-latest
        steps: 
            - name: Print greeting
              run: | 
                echo  Salut Reda 
                echo welcome to this course
            - name: Print Good bye 
              run: echo bye bye 
