name: main-1 worklflow


on:
    workflow_dispatch:
    # [push, workflow_dispatch]:
        inputs: 
            ENV:
              required: true  
              type: choice
              description: environement 
              options: 
                - dev
                - nprod
                - prod
            action:
              required: true  
              type: choice
              description: action
              options: 
                - deploy
                - destroy
                - update


jobs:
    first-job:
        runs-on: ubuntu-latest
        steps: 
            - name: Print greeting
              run: | 
                echo  Salut Reda from ${{ github.workflow }} avec comme option ${{inputs.ENV}} et ${{inputs.action}}
                echo welcome to this course
            - name: liste le code 
              uses: actions/checkout@v3
            - name: Print Good bye 
              run: |
                ls -l 
                echo bye bye 

    deploy-dev :
        if: ${{ ( inputs.ENV == 'dev') && ( inputs.action == 'deploy') }}
        uses: ./.github/workflows/template.yml
        with:
            ENV: ${{ inputs.ENV }}
            ACTION: ${{ inputs.action }}
        secrets:     
            sa_172 : ${{ secrets.SA_TEST172 }}