name: template 

on:
    workflow_call:
        inputs: 
            ENV:
              required: true  
              type: string


jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            - name : first-step
              run : 
                echo coucou pour l'environment ${{ inputs.ENV }}
