name: template 

on:
    workflow_call:
        inputs: 
            ENV:
              required: true  
              type: string
            ACTION:
              required: true  
              type: string



jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            - name : first-step
              run : 
                echo coucou pour lenvironment ${{ inputs.ENV }} et l action ${{ inputs.ACTION }}
              env:
                sa_172 : ${{ secrets.SA_TEST172}}